
'use client';

import { useState, useEffect, useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import { Save, Printer, RefreshCw, Loader2 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { useCompany } from '@/context/company-context';
import type { CompanyInfo, ReportSettings } from '@/lib/types';
import { updateCompanyInfo } from '@/services/settings';

const defaultSettings: ReportSettings = {
    headerText: 'This is a computer-generated report. No signature is required.',
    footerText: 'Page {currentPage} of {totalPages}',
    showWatermark: true,
    showCompanyName: true,
    showCompanyAddress: true,
    reportTitle: 'Report',
};


// Mock data for the live preview
const mockReportData = {
  title: 'Sales Report',
  dateRange: '01 Aug 2025 - 21 Aug 2025',
  generatedBy: 'Admin',
  items: [
    { id: 1, date: '2025-08-20', invoice: 'INV-001', customer: 'John Doe', amount: 150.00 },
    { id: 2, date: '2025-08-21', invoice: 'INV-002', customer: 'Jane Smith', amount: 200.00 },
  ],
  total: 350.00,
};

const ReportPreview = ({ settings, companyInfo }: { settings: ReportSettings, companyInfo: CompanyInfo | null }) => {
    return (
        <div id="report-preview" className="w-full bg-white p-6 shadow-lg text-black relative">
            {settings.showWatermark && <div className="absolute inset-0 flex items-center justify-center text-8xl font-bold text-gray-200 opacity-50 transform -rotate-45 pointer-events-none">DRAFT</div>}
            <header className="text-center mb-6 border-b pb-4">
                 {companyInfo && (
                    <div className="mb-4">
                        {settings.showCompanyName && <h2 className="text-2xl font-bold">{companyInfo.name}</h2>}
                        {settings.showCompanyAddress && <p className="text-xs">{companyInfo.address}</p>}
                    </div>
                )}
                <h1 className="text-xl font-bold">{settings.reportTitle || mockReportData.title}</h1>
                <p className="text-sm">For the period: {mockReportData.dateRange}</p>
                <p className="text-xs mt-2">{settings.headerText}</p>
            </header>

            <table className="w-full text-left text-sm mb-6">
                <thead>
                    <tr>
                        <th className="py-2 font-semibold">Date</th>
                        <th className="py-2 font-semibold">Invoice #</th>
                        <th className="py-2 font-semibold">Customer</th>
                        <th className="py-2 text-right font-semibold">Amount</th>
                    </tr>
                </thead>
                    <tbody>
                    {mockReportData.items.map(item => (
                        <tr key={item.id}>
                            <td className="py-2">{item.date}</td>
                            <td className="py-2">{item.invoice}</td>
                            <td className="py-2">{item.customer}</td>
                            <td className="py-2 text-right">${item.amount.toFixed(2)}</td>
                        </tr>
                    ))}
                </tbody>
                <tfoot>
                    <tr className="font-bold">
                        <td colSpan={3} className="pt-2 text-right">Total:</td>
                        <td className="pt-2 text-right">${mockReportData.total.toFixed(2)}</td>
                    </tr>
                </tfoot>
            </table>

            <footer className="text-center text-xs text-gray-500 border-t pt-4 mt-6">
                <p>Generated by: {mockReportData.generatedBy}</p>
                <p>{settings.footerText.replace('{currentPage}', '1').replace('{totalPages}', '1')}</p>
            </footer>
            </div>
    )
}

export default function ReportSettingsPage() {
  const { toast } = useToast();
  const { companyInfo, refreshCompanyInfo } = useCompany();
  const [settings, setSettings] = useState<ReportSettings>(defaultSettings);
  const [isSaving, setIsSaving] = useState(false);

  useEffect(() => {
    if (companyInfo?.reportSettings) {
        setSettings(companyInfo.reportSettings);
    }
  }, [companyInfo]);

  const handleSave = async () => {
    if (!companyInfo) return;
    setIsSaving(true);
    try {
        const updatedInfo: Partial<CompanyInfo> = {
            id: companyInfo.id,
            reportSettings: settings
        };
        await updateCompanyInfo(updatedInfo as CompanyInfo);
        await refreshCompanyInfo();
        toast({ title: 'Success', description: 'Report settings saved successfully.' });
    } catch (error) {
        toast({ variant: 'destructive', title: 'Error', description: 'Failed to save settings.' });
    } finally {
        setIsSaving(false);
    }
  };

  const handleReset = () => {
    setSettings(defaultSettings);
    toast({ title: 'Resetted', description: 'Settings have been reset to default values.' });
  }

  const handlePrint = () => {
    const printContent = document.getElementById('report-preview');
    if (printContent) {
        const originalContents = document.body.innerHTML;
        document.body.innerHTML = printContent.innerHTML;
        window.print();
        document.body.innerHTML = originalContents;
        window.location.reload(); 
    }
  }

  const handleSettingChange = (key: keyof typeof settings, value: any) => {
    setSettings(prev => ({ ...prev, [key]: value }));
  };


  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <div className="lg:col-span-1 space-y-6">
        <Card>
          <CardHeader>
            <CardTitle>Report Print Settings</CardTitle>
            <CardDescription>Customize the header, footer, and other print elements for your reports.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
             <div className="grid gap-2">
                <Label htmlFor="report-title">Default Report Name</Label>
                <Input id="report-title" value={settings.reportTitle} onChange={(e) => handleSettingChange('reportTitle', e.target.value)} placeholder="e.g., Sales Report"/>
            </div>
             <div className="grid gap-2">
                <Label htmlFor="header-text">Header Text</Label>
                <Textarea id="header-text" value={settings.headerText} onChange={(e) => handleSettingChange('headerText', e.target.value)} placeholder="Enter text to show on the report header..."/>
            </div>
             <div className="grid gap-2">
                <Label htmlFor="footer-text">Footer Text</Label>
                <Textarea id="footer-text" value={settings.footerText} onChange={(e) => handleSettingChange('footerText', e.target.value)} placeholder="Enter text to show on the report footer..."/>
                 <p className="text-xs text-muted-foreground">Use {'{currentPage}'} and {'{totalPages}'} for dynamic page numbers.</p>
            </div>
            <div className="flex items-center justify-between">
                <Label htmlFor="show-watermark">Show "Draft" Watermark</Label>
                <Switch id="show-watermark" checked={settings.showWatermark} onCheckedChange={(c) => handleSettingChange('showWatermark', c)} />
            </div>
             <div className="flex items-center justify-between">
                <Label htmlFor="show-company-name">Show Company Name</Label>
                <Switch id="show-company-name" checked={settings.showCompanyName} onCheckedChange={(c) => handleSettingChange('showCompanyName', c)} />
            </div>
             <div className="flex items-center justify-between">
                <Label htmlFor="show-company-address">Show Company Address</Label>
                <Switch id="show-company-address" checked={settings.showCompanyAddress} onCheckedChange={(c) => handleSettingChange('showCompanyAddress', c)} />
            </div>
          </CardContent>
           <CardFooter className="flex gap-2 border-t pt-6">
                <Button onClick={handleSave} disabled={isSaving}>
                    {isSaving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}
                    Save Settings
                </Button>
                <Button variant="outline" onClick={handleReset}>
                    <RefreshCw className="mr-2 h-4 w-4" /> 
                    Reset
                </Button>
            </CardFooter>
        </Card>
      </div>

      <div className="lg:col-span-2">
        <Card className="sticky top-6">
            <CardHeader className="flex flex-row justify-between items-center">
                 <CardTitle>Live Preview</CardTitle>
                 <div className="flex gap-2">
                    <Button variant="outline" onClick={handlePrint}><Printer className="mr-2 h-4 w-4" /> Print Preview</Button>
                 </div>
            </CardHeader>
          <CardContent className="bg-muted/30 p-8">
             <ReportPreview settings={settings} companyInfo={companyInfo} />
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
